import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs';
import './globals.css';

// Configure the Inter font
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        <ClerkProvider>
          {/* Header Section */}
          <header className="bg-blue-600 text-white p-4 shadow-md">
            <div className="container mx-auto flex justify-between items-center">
              <h1 className="text-2xl font-bold">My App</h1>

              <div>
                <SignedOut>
                  <SignInButton className="text-white bg-blue-700 hover:bg-blue-800 py-2 px-4 rounded">
                    Sign In
                  </SignInButton>
                </SignedOut>
                
                <SignedIn>
                  <UserButton />
                </SignedIn>
              </div>
            </div>
          </header>

          {/* Main Content Section */}
          <main className="container mx-auto p-6">
            {children}
          </main>
        </ClerkProvider>
      </body>
    </html>
  );
}
